version: '3.4'

services:

  enricher.db:
    image: postgres
    container_name: Template.DbApi.Db
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    networks:
      - main

  enricher.seq:
    image: datalust/seq
    container_name: Template.DbApi.Seq
    ports:
      - "5030:80"
    environment:
      - ACCEPT_EULA=Y
    networks:
      - main

  enricher.adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - main

  # For more on Keycloak: https://www.keycloak.org/getting-started/getting-started-docker
  enricher.keycloak:
    depends_on:
      - enricher.db
    container_name: Template.DbApi.Keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    image: quay.io/keycloak/keycloak:21.1.0
    command: 
      - start-dev 
    ports:
      - "28080:8080"
    networks:
      - main

networks:
    main: