version: '3.4'

services:

  enricher.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - http://+:80
      - Serilog__WriteTo__0__Args__serverUrl=http://Template.DbApi.Seq
      - Postgres__WriteConnection=Host=Template.DbApi.Db;Port=5432;Username=postgres;Password=example;Database=shop;
      - Postgres__ReadConnection=Host=Template.DbApi.Db;Port=5432;Username=postgres;Password=example;Database=shop;
    ports:
      - "5080:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - main

  enricher.dbup:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DbConnectionString=Host=Template.DbApi.Db;Port=5432;Username=postgres;Password=example;Database=shop;
    networks:
      - main

networks:
    main: