
name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ??
on: [push]
jobs:
  Pack-And-Push-Template:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
  
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Run cake step
        uses: cake-build/cake-action@v1
        with:
            script-path: template.cake
            target: PackAndPushTemplate